### ISSUE TITLE
Remove node_modules from the repository

### ISSUE THREAD

**Issue by fluxsauce** [c0mputer-junkie/meal-engine#44]
*Warning!* This literally alters history! If you do this, you won't be able to merge from existing forks and anyone who is working from this repository will need to remove the project and reclone.

With that said, `node_modules` shouldn't be committed to your custom code directory.

Source: https://stackoverflow.com/a/17824718 with one alteration (`.gitignore`)

```bash
git filter-branch --tree-filter 'rm -rf node_modules' --prune-empty HEAD
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
curl --url https://raw.githubusercontent.com/github/gitignore/master/Node.gitignore --output .gitignore
git add .gitignore
git commit -m 'Removing node_modules from git history'
git gc
git push origin master --force
```

When you're done, update the setup instructions to include `npm install`.

**Comment by smcueto** [comment]
It has been done! :)
