### ISSUE TITLE
Replace hotlinked images with images in local repository

### ISSUE THREAD

**Issue by fluxsauce** [c0mputer-junkie/meal-engine#45]
In short, those are not public sources and could break at any time.

Place the images in `public/img` or similar.

- `views/index.js` - https://emojipedia-us.s3.amazonaws.com/thumbs/160/facebook/65/fork-and-knife_1f374.png - replace with `/img/fork-and-knife_1f374.png`
- `public/css/main.css` - http://blog.retreat.guru/wp-content/uploads/2015/11/Dollarphotoclub_70594694-1200x700.jpg - for the purposes of this project, it's okay to use `http://localhost:3000/img/Dollarphotoclub_70594694-1200x700.jpg`

**Comment by smcueto** [comment]
Updated it!
